### ISSUE TITLE
installation pypi issue

### ISSUE THREAD

**Issue by meChiel** [oeway/ImJoy-Engine#10]
Hey 

I saw your presentation at Neubias. Looks very interesting. Was trying to give it a try.
Some examples on the imJoy website really work just by going to the website and run it. Amazing.
I was trying to run also some more advanced examples e.g. CARE. As I understood so far, some examples require me to install ImJoy plugin engine.
When trying to start the imJoy Plugin Engine in the desktop app, I got the next error.

Successfully uninstalled imjoy-0.7.25

Successfully installed imjoy-0.7.25
pip is configured with locations that require TLS/SSL, however, the ssl module in Python is not available.

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

Traceback (most recent call last): File "C:\Users\mvandyc5\ImJoyApp\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "C:\Users\mvan
![imjoy error](https://user-images.githubusercontent.com/5637172/52568346-c91c3680-2e0e-11e9-92d7-7657aee411c1.png)
dyc5\ImJoyApp\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\imjoy\__main__.py", line 66, in <module> main() File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\imjoy\__main__.py", line 15, in main from .imjoyPluginEngine import main File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\imjoy\imjoyPluginEngine.py", line 3, in <module> import socketio File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\socketio\__init__.py", line 3, in <module> from .client import Client File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\socketio\client.py", line 5, in <module> import engineio File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\engineio\__init__.py", line 3, in <module> from .client import Client File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\engineio\client.py", line 17, in <module> import websocket File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\websocket\__init__.py", line 23, in <module> from ._app import WebSocketApp File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\websocket\_app.py", line 36, in <module> from ._core import WebSocket, getdefaulttimeout File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\websocket\_core.py", line 34, in <module> from ._handshake import * File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\websocket\_handshake.py", line 30, in <module> from ._http import * File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\websocket\_http.py", line 31, in <module> from ._socket import* File "C:\Users\mvandyc5\ImJoyApp\lib\site-packages\websocket\_socket.py", line 28, in <module> from ._ssl_compat import * AttributeError: module 'websocket._ssl_compat' has no attribute 'ssl'

Upgrading ImJoy Plugin Engine...

Process 'Starting ImJoy Plugin Engine 🚀...' exited with code: 1)

**Comment by oeway** [comment]
Hey, thanks for testing it.

Right, we have been experiencing some SSL related error on windows (only), and I tried to fix for the [conda SSLError](https://github.com/conda/conda/issues/6064#issuecomment-458389796), but apperently pip is also affected. 

I have just deployed [a new commit](https://github.com/oeway/ImJoy-Engine/commit/11ccacd874d2eb3a6f3b96c06d354e9119cd449d) try to fix this problem, but I don't have a window machine to test, would be good if you can try it with the following steps:
1. Remove a folder called `ImJoyApp` located in `C:\Users\username`, that will give the installation a new start.
2. Try to install it again from the `ImJoy-App`, you don't need to download again, just use the same one should work.
3. See it it fixes the problem

If that doesn't work, then please try to edit your system environment variables `path` ([HOWTO](https://www.computerhope.com/issues/ch000549.htm)). What you need to do is to add `C:\Users\USERNAME\ImJoyApp\Library\bin` to your `path`. Please replace the above USERNAME with your actual user name, the easiest if to find the `bin` folder and copy the path, make sure in the end you have something like:
`C:\Users\USERNAME\ImJoyApp\Library\bin;C:\Program Files;C:\Winnt;C:\Winnt\System32`.

Please let me know whether it works for you, and what you did. Thanks.

**Comment by meChiel** [comment]
Yes it worked.
I clicked, engine install again and now it rsulted in:
![imjoy solution2](https://user-images.githubusercontent.com/5637172/52571583-1b148a80-2e16-11e9-9be5-51b81e134e42.png)


![imjoy solution](https://user-images.githubusercontent.com/5637172/52571487-f0c2cd00-2e15-11e9-9c6d-13fa5d7f0252.png)

Thanks for the very fast fix.

Kr Michiel

**Comment by meChiel** [comment]
Oh wait a sec; maybe it is not fixed;

**Comment by oeway** [comment]
Hey, thanks for the detailed report, I missed one place, sorry about that. I just deployed another fix for that.

Please try to reinstall it, and it should work, please let me know, thanks.

**Comment by meChiel** [comment]
I think it is working now.
Thanks again.

Kr Michiel

**Comment by oeway** [comment]
Ok, good to hear that it works, let me know if you have any other question.

And please close this issue if you confirm this issue is resolved after more tests.

**Comment by meChiel** [comment]
Thanks it's working now.
