### ISSUE TITLE
Manual installation problem

### ISSUE THREAD

**Issue by aaristov** [oeway/ImJoy-Engine#9]
Hi,

I followed the instruction for manual installation of plugin engine using miniconda.

If I do

`pip install -U git+https://github.com/oeway/ImJoy-Engine#egg=imjoy`

and 

`python -m imjoy`

I get the error:

`ModuleNotFoundError: No module named 'yaml'`

Submitted [pull request](https://github.com/oeway/ImJoy-Engine/pull/8/commits/f355890b64a25521ca40964bc5e2bfc8269b0013)

**Comment by oeway** [comment]
merged.
